name: Timed Commit

on:
  schedule:
    - cron: '0 0 */5 * *'  # Run every 5 days at midnight

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: Checkout repository
      uses: actions/checkout@v2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update date file
      run: |
        echo $(date) > current_date.txt
        git add current_date.txt
        git commit -m "Update current date" -m "Attempt to avoid streamlit freeze" || true
        git push