name: Timed Commit

on:
  schedule:
    - cron: '0 0 */5 * *'  # Run every 5 days at midnight
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: Checkout repository
      uses: actions/checkout@v2
      env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

    - name: Update date file
      run: |
        echo $(date) > current_date.txt
        git add current_date.txt
        git commit -m "Update current date" -m "Attempt to avoid streamlit freeze" || true

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT_TOKEN }}
        branch: ${{ github.ref }}