[theme]
base="light"
primaryColor = "#1DB954"
backgroundColor = "#191414"
secondaryBackgroundColor = "#000000"
textColor = "#DCDCDC"
font = "sans serif"

[server]
headless = true
enableCORS=true
enableXsrfProtection=false
port = 8463

[deprecation]
showPyplotGlobalUse = false

[global]
dataFrameSerialization = "legacy"
